### ISSUE TITLE
Ch2's setup won't work for Ch3

### ISSUE THREAD

**Issue by seadoherty** [bootstrapping-microservices/chapter-3#3]
@ashleydavis 
I error-ed out progressing through the book until I looked at this repo's package.json
Wanted to give you a heads in case others run into this
It may be helpful to have a note to the learner about creating src/ and putting index.js in there
Then have them update package.json like below
This way the Dockerfile can stay the same as it is in this repo w/working directory and copying

CH2: 
`
  "scripts": {
    "start": "node index.js",
    "start:dev": "nodemon index.js"
  }
`
CH3: 
`
  "scripts": {
    "start": "node ./src/index.js",
    "start:dev": "nodemon ./src/index.js"
  }
`

**Comment by ashleydavis** [comment]
Thanks for letting me know. I'll put this one down for the next release of the book.

**Comment by ashleydavis** [comment]
@seadoherty Just letting you know I've started working towards a 2nd edition of Bootstrapping Microservices so I'm going to take this feedback into account.

If you have other feedback please reach out to me on ashley@codecapers.com.au.
